superProject/apple/urls.py
from django.urls import path
from .views import apple_page, category_sort,product_detail, less_forms,less_shops,category_form,\
        product_form, shop_form,form_category,form_model

app_name = 'apple'

urlpatterns = [
        path('', apple_page, name='apple_page'),
        path('<int:id>/', category_sort, name = "category_sort"),
        path('product_detail/<int:id>/', product_detail, name = 'product_detail'),
        path('less_forms/', less_forms, name='less_forms'),
        path('less_forms/<int:id>/', product_detail, name = 'product_detail' ),
        path('category_form/', category_form, name='category_form'),
        path('product_form/', product_form, name='product_form'),
        path('shop_form/', shop_form, name='shop_form'),
        path('form_category/', form_category, name='form_category'),
        path('form_model/', form_model, name='form_model'),

]

superProject/superProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
# from apple.views import get_apple
from main.views import get_main
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('apple/', include('apple.urls')),
    path('new_app/', include('new_app.urls')),
    path('', get_main),


]

# для загрузки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superProject/apple/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name="Категория")

    def __str__(self):
        return self.name


class Product(models.Model):
    KINDS = (
        ('Выбор 1', 'Выбор 1'),
        ('Выбор 2', 'Выбор 2'),
    )

    title = models.CharField(max_length=250, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    price = models.DecimalField(max_digits=6,decimal_places=2, verbose_name="Цена")
    image= models.ImageField(upload_to='images', null=True, verbose_name="Изображения")
    created = models.DateTimeField(auto_created=True, verbose_name="Дата")
    update=models.DateTimeField(auto_now=True)
    categories = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="Категория")
    kind = models.CharField(max_length=7, choices=KINDS, default='Выбор 1' ,verbose_name="Список")


    def __str__(self):
        return self.title


class Shop(models.Model):
    name = models.CharField(max_length = 30, verbose_name="Название")
    citi = models.CharField(max_length = 30, verbose_name="Город")
    street = models.CharField(max_length = 30, verbose_name="Адресс")
    products = models.ManyToManyField('Product')

    def __str__(self):
        return self.name

# Create your models here.

superProject/main/models.py
from django.db import models


class Droid(models.Model):
    name = models.CharField(max_length=20)
    master = models.CharField(max_length=20)
    planet = models.CharField(max_length=30)
    image = models.ImageField(null=True, blank=True,upload_to='images')


class User(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    age = models.CharField(max_length=10)
    city = models.CharField(max_length=20)
    # sex =

class Auto(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    master = models.CharField(max_length=20)
    color = models.CharField(max_length=20)



# Create your models here.

superProject/new_app/models.py
from django.db import models



class Person(models.Model):
    nik_name = models.CharField(max_length=30, verbose_name="Имя профиля")
    login = models.CharField(max_length=20, verbose_name="Логин", unique=True)
    password = models.CharField(max_length=30, verbose_name="Пароль")
    avatar = models.ImageField(upload_to='images', null=True, verbose_name="Фото профиля")

    def __str__(self):
        return self.nik_name


class A(models.Model):
    name = models.CharField(max_length=30, verbose_name="Имя профиля")
    age = models.PositiveIntegerField

superProject/apple/forms.py
from django import forms
from django.core.exceptions import ValidationError
from apple.models import Product


def valid_name(name):
    if name=="johan":
        print(name)
    else:
        raise ValidationError("error name")

class CategoryForm(forms.Form):
    name = forms.CharField(label='Категория', max_length=100, validators=[valid_name])
    password = forms.CharField(widget=forms.PasswordInput)
    price = forms.DecimalField(max_digits=6,decimal_places=2, label='Цена')

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields=['title','description','price','image','categories','kind','created']

superProject/apple/views.py
from django.shortcuts import render, redirect
from apple.models import Category, Product, Shop
from .forms import CategoryForm,ProductForm

def apple_page (request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories' : categories,
        'products': products
    }

    return render(request, 'apple.html', context)

def category_sort(request,id):
    categories = Category.objects.all()
    products = Product.objects.filter(categories=id)
    context = {"products":products,
               'categories' : categories,}

    return render(request, "categories.html",context)

def product_detail(request, id):
    product = Product.objects.get(id =id)
    shop =  product.shop_set.all

    context = {'product':product,
               'shops': shop
               }

    return render(request, 'product_detail.html', context)


def less_forms(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    shop = Shop.objects.all()
    form = CategoryForm()
    context = {
        'categories': categories,
        'products': products,
        'shop': shop,
        'form': form,
    }

    if request.method =='POST':

        title = request.POST.get('Title')
        discription = request.POST.get('discription')
        price = request.POST.get('price')
        created = request.POST.get('created')
        categories = request.POST.get('categories')
        img = request.POST.get('img')
        kind = request.POST.get('kind')
        add_forms(title,discription,price,created,categories,img,kind)

    else:
        pass

    return render(request, 'less_forms.html', context)



def less_shops(request):
    products = Product.objects.all()
    shop = Shop.objects.all()
    form = CategoryForm()
    context = {
        'products': products,
        'shop': shop,
        'form': form,
        }


    return render(request, 'less_shops.html', context)



def category_form(request):

    return redirect('apple:less_forms')

def product_form(request):

    return redirect('apple:less_forms')

def shop_form(request):

    return redirect('apple:less_forms')


def form_category(request):
    form = CategoryForm()
    context ={
        'form':form,
    }
    if request.method =='POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
        else:
            print(form.error)

    # return redirect('apple:less_forms')
    return render(request,'form_error.html', context)

def form_model(request):
    form = ProductForm()
    context ={
        'form':form,
    }
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
    return render(request, 'model_form.html',context)

superProject/apple/templates/apple.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Market_Python</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
<header id="header">
    <div class="apple">
        <img src="{% static 'img/logo.jpg'%}" alt="" class="header_logo"></div>
    <strong>Hello</strong>
    <div class="apple"><a href="{% url 'apple:form_model' %}">Модель </a></div>
    <div class="apple"><a href="{% url 'apple:less_forms' %}">Форма для добавления товаров</a></div>
</header>
<nav class="nav">
    <ul class="nav_ul">
        <li class="navigation_li"><a href="{% url 'apple:apple_page' %}">Все</a></li>
        {% for cat in categories %}
        <li class="navigation_li"><a href="{% url 'apple:category_sort' cat.id %}"> {{cat.name}} </a></li>
        {% endfor %}



    </ul>
</nav>
<main class="main">
    {% block content %}
    {% for prod in products %}

    <div class="item_img">
        <a href="{% url 'apple:product_detail' prod.id %}">
        <img src="{{ prod.image.url}}" alt="не найдено" class="img">
        <p>{{ prod.title }}</p>
        <p>{{ prod.created }}</p>
        <p>{{ prod.categories }}</p>
        <p>{{ prod.kind }}</p>
        <p>Цена {{ prod.price }} $</p>
            </a>
    </div>
    {% endfor %}
    {% endblock %}



</main>
</body>




</html>

superProject/apple/templates/categories.html
{% extends 'apple.html' %}


  {% block content %}
    {% for prod in products %}
    <div class="item_img">
        <a href="{% url 'apple:product_detail' prod.id %}">
        <img src="{{ prod.image.url}}" alt="" class="img">
        <p>{{ prod.title }}</p>
        <p>{{ prod.created }}</p>
        <p>{{ prod.categories }}</p>
        <p>{{ prod.kind }}</p>
        <p>{{ prod.price }}</p>
    </div>
    {% endfor %}
    {% endblock %}

superProject/apple/templates/form_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
<form action="{% url 'apple:form_category' %}" method="POST">
        {% csrf_token %}
        {{ errors }}
        {{ form.as_p }}

        <button>Ok Form</button>
    </form>


</body>
</html>

superProject/apple/templates/less_forms.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>less-forms</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
        </head>


    <body>

<div class="ttl">
    <h1>Форма class FORM</h1>
    <form action="{% url 'apple:form_category' %}" method="POST">
        {% csrf_token %}
        {{ errors }}
        {{ form.as_p }}

        <button>Ok Form</button>
    </form>

</div>
</body>
</html>

superProject/apple/templates/less_shops.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Less_Shops</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <h1 class="ttl">Hello less_forms</h1>
    <div class="ttl"
    <h2 class="ttl"> Существующие категории </h2><br>
        {% for cat in categories %}
        <a href="{% url 'apple:category_sort' cat.id %}"> {{cat.name}} </a>
        {% endfor %}
    </div>

    <div class="forms">
        <h2 class="ttl"> Категории </h2>
        <form action="{% url 'apple:category_form' %}" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="Введите название" name="Title">Название категории<br>
            <input type="reset" name="reset"><br>
            <button>OK</button>
        </form>
    </div>

    <div class="ttl">
        <h2>Списачэк уже имеющихся продуктов</h2>
        {% for prod in products %}
        <a href="{% url 'apple:product_detail' prod.id %}">{{ prod.title }}</a>
        {% endfor %}
    </div>

    <div class="forms">
        <h1 class="ttl">Продукты</h1>
        <form action="{% url 'apple:product_form' %}" method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            <input type="text" placeholder="Введите название" name="Title">Название товара<br>
            <p>Описание</p>
            <textarea name="discription">Описание</textarea><br>
            <input type="number" name="price">Цена <br>
            <input type="file" name="img" accept="image/jpeg,image/png">Изображение <br>
            <input type="date" name="created">Дата и Время<br>

            Категория<br>

            <select id="Category"name="categories"><br>
                {% for cat in categories %}
                <option value="{{cat.id}}">{{cat.name}}</option><br>
                {% endfor %}
            </select>
            <input type="radio" name="kind" value="Выбор 1">Выбор 1<br>
            <input type="radio" name="kind" value="Выбор 2">Выбор 2<br>

            <input type="reset" name="reset"><br>
            <button>OK</button>

    </form>
    </div>

<div class="ttl">
    <h2> Все магазины</h2>
    {% for i in shop %}
        <a href="">{{ i.name }}</a>
        {% endfor %}

</div>

<div class="forms">
    <h1 class="ttl">Магазины</h1>
    <form action="" method="POST">

        {% csrf_token %}
        <input type="text" placeholder="Введите название" name="name">Название магазина<br>
        <input type="text" placeholder="Введите город" name="citi">Город<br>
        <input type="text" placeholder="Введите адресс" name="street">Адресс<br>

        {% for p in products %}
            <input type="checkbox" name="product" value="{{p.id}}">{{p.title}}</input><br>

        {% endfor %}
        </select>

        <input type="reset" name="reset"><br>
        <button>OK</button>
    </form>
</div>

</body>
</html>

superProject/apple/templates/model_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Model</title>
</head>
<body>
<h1>Форма по ModelForm</h1>
<form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button>OK ModelForm</button>
    </form>

</body>
</html>

superProject/apple/templates/product_detail.html
{% extends 'apple.html' %}


{% block content %}
<h>Детализация товара</h>
    <div class="item_img">

        <img src="{{ product.image.url}}" alt="" class="img">
        <p>{{ product.title }}</p>
        <p>{{ product.created }}</p>
        <p>{{ product.categories }}</p>
        <p>{{ product.kind }}</p>
        <p>{{ product.price }}</p>
        {% for m in shops %}
            <p>{{ m.name }}</p>
        {% endfor %}

    </div>

    {% endblock %}